name: DiscordStatusBot

services:
  discord_bot1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord_bot
    env_file:
      - .env
    volumes:
      - ./DiscordBot:/app
    working_dir: /app
    command: python3 Website Status Checker.py
    restart: unless-stopped
